CREATE TABLE USUARIOS(
	ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT	,
    CD_USUARIO VARCHAR(20) NOT NULL UNIQUE		,
    NM_USUARIO VARCHAR(100) NOT NULL			,
    SENHA VARCHAR(255) NOT NULL					,
    DT_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO USUARIOS(CD_USUARIO, NM_USUARIO, SENHA) VALUES ("62998215623", "Gabriel Sales", SHA1("123456"));
SELECT * FROM USUARIOS;

DELIMITER $$
CREATE PROCEDURE LOGIN_USUARIO(
	IN IN_CD_USUARIO VARCHAR(20)	,
    IN IN_SENHA VARCHAR(255)		
)
BEGIN
	SELECT
		US.ID_USUARIO	,
		US.NM_USUARIO
	FROM USUARIOS US WHERE
		US.CD_USUARIO = IN_CD_USUARIO AND
		US.SENHA = SHA1(IN_SENHA);
END $$
DELIMITER ;

CALL LOGIN_USUARIO("62998215623","123456");

DELIMITER $$
CREATE PROCEDURE INSERT_USUARIO(
	IN IN_CD_USUARIO VARCHAR(20)	,
    IN IN_NM_USUARIO VARCHAR(100)	,
    IN IN_SENHA VARCHAR(255)
)
BEGIN
	INSERT INTO USUARIOS (
		CD_USUARIO	,
        NM_USUARIO	,
        SENHA		)
	VALUES (
		IN_CD_USUARIO	,
        IN_NM_USUARIO	,
        SHA1(IN_SENHA)	);
END $$
DELIMITER ;