-- Tabela de usuários do sistema
CREATE TABLE USUARIOS (
	ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT	,
    CD_USUARIO VARCHAR(20) NOT NULL UNIQUE		,
    NM_USUARIO VARCHAR(100) NOT NULL			,
    SENHA		VARCHAR(255) NOT NULL			,
    DT_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Procedure para criação de usuário
DELIMITER $$
CREATE PROCEDURE INSERT_USUARIO(
	IN IN_CD_USUARIO VARCHAR(20)	,
    IN IN_NM_USUARIO VARCHAR(100)	,
    IN IN_SENHA_HASH VARCHAR(250)	
    )
    BEGIN
		INSERT INTO USUARIOS (
			CD_USUARIO	,
            NM_USUARIO	,
            SENHA
		) VALUES (
			IN_CD_USUARIO	,
            IN_NM_USUARIO	,
            IN_SENHA_HASH 
		);
	
    -- Retorna último usuário criado para login
    SELECT ID_USUARIO, NM_USUARIO FROM USUARIOS WHERE ID_USUARIO = LAST_INSERT_ID();
    END $$
DELIMITER ;

-- Procedure para login de usuário
DELIMITER $$
CREATE PROCEDURE LOGIN_USUARIO(
	IN IN_CD_USUARIO VARCHAR(20)
    )
    BEGIN
		SELECT
			ID_USUARIO	,
            NM_USUARIO	,
            SENHA
		FROM USUARIOS WHERE
			CD_USUARIO = IN_CD_USUARIO;
	END $$
DELIMITER ;